services:
  - type: web
    name: recruvia
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /_stcore/health
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GMAIL_SENDER
        sync: false
      - key: GMAIL_PASSWORD
        sync: false